spring.application.name=OauthDemo

spring.security.oauth2.client.registration.google.client-id=587915398879-drnr8h5lg5nn5dpo62pu89378kukg80h.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
